from typing import List

ROOM_ALL: List[int] = [10, 2, 4, 3, 6, 7, 8, 1, 5]
ROOM_ALL_CAN_BOOK: List[int] = [10, 2, 4, 3, 7, 9, 1]

ROOM_TYPE_STUDYROOM = 1
ROOM_TYPE_SEMINARROOM = 2
ROOM_TYPE_STUDIOROOM = 3
ROOM_TYPE_ALL: List[int] = [ROOM_TYPE_STUDYROOM, ROOM_TYPE_SEMINARROOM, ROOM_TYPE_STUDIOROOM]
